### ISSUE TITLE
Can you also build for berlin ie edge 20

### ISSUE THREAD

**Issue by Shubhamkr4** [forforksake/recovery_device_motorola_kyoto#1]
I will be testing it although Im not a developer so you do have to provide me with installation instructions too.

**Comment by forforksake** [comment]
> I will be testing it although Im not a developer so you do have to provide me with installation instructions too.

what device is that?

**Comment by Shubhamkr4** [comment]
> > I will be testing it although Im not a developer so you do have to provide me with installation instructions too.
> 
> what device is that?

Edge 20
